### ISSUE TITLE
Display toggle 

### ISSUE THREAD

**Issue by Orneeman** [lizardsystems/midea-mini-dongle#5]
Hi,
I've been testing the -midea_ac-2022.1.2.bin binary on my AC unit, and it seems like the display toggling off feature isn't functioning when controlled via UART. All other features are working seamlessly.

Would appreciate some insights or guidance on this.

**Comment by vzagorovskiy** [comment]
Many air conditioners do not support display toggling via UART as mentioned https://esphome.io/components/climate/midea.html#midea-ac-display-toggle-action

My air conditioners do not :(

You may add the following code to midea_ac.yaml and rebuild the firmware yourself  

```yaml
button:
  - platform: template
    name: ${friendly_node_name} Display Toggle
    icon: mdi:theme-light-dark
    on_press:
      midea_ac.display_toggle:      

```
